--- 
abstract: Automatically generate documentation stubs for Moose-based classes.
author: 
  - =over 4
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: MooseX-AutoDoc
no_index: 
  directory: 
    - inc
    - t
requires: 
  Moose: 0.36
  Template: 0
version: undef
